### ISSUE TITLE
Cloudflare will automatically re-verify all the time

### ISSUE THREAD

**Issue by SyaoranChang** [kawa-nobu/Clean-Spam-Link-Tweet#13]
Hi,

Version 1.9.2
I've got a issue.
Cloudflare will automatically re-verify all the time

Example Websites
https://www.dcard.tw/

**Comment by kawa-nobu** [comment]
Hello.
Regarding the Cloudflare bug, where in CSLT is it occurring?
I would appreciate a screenshot if you don't mind.

**Comment by SyaoranChang** [comment]
Hi,

This is the process I encountered
Cloudflare will always reload automatically.

![Snipaste_2024-04-15_11-14-47](https://github.com/kawa-nobu/Clean-Spam-Link-Tweet/assets/18550228/a36181dd-a7f8-43ab-8f38-fa3f4edceef7)



`GET
https://www.dcard.tw/f
[HTTP/3 403  12ms]

Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://www.dcard.tw/f?__cf_chl_rt_tk=BRKRh9TreTQdxoIMr1yTADmbSqgLOlJ99OXUwZxGwNo-1713150605-0.0.1.1-1279:1
f:1:445
Source map error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://7392272a-fd93-4a56-acc2-c9e71fb9b7c7/model/static/DOMPurify/purify.min.js
Source Map URL: purify.min.js.map

ReferenceError: jQuery is not defined
selection.js:28:449
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “cf_chl_3” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite v1:1:372747
Cookie “cf_chl_3” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite v1:1:372326
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. api.js:1:32627
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. api.js:1:32665
Feature Policy: Skipping unsupported feature name “cross-origin-isolated”. api.js:1:32864
Partitioned cookie or storage access was provided to “https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/a3tr7/0x4AAAAAAAAjq6WYeRDKmebM/light/normal” because it is loaded in the third-party context and dynamic state partitioning is enabled.

[[[ERROR]]]: Message: ReferenceError: jQuery is not defined - URL: https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/a3tr7/0x4AAAAAAAAjq6WYeRDKmebM/light/normal - Line: 1 - Column: 445 - Error object: {} v1:1:3277
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/a3tr7/0x4AAAAAAAAjq6WYeRDKmebM/light/normal:1
normal:1:445
XML Parsing Error: no root element found
Location: https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/beacon/ov1/496730348:1713148261:9Z4IkKzQ0qgns1yKST5wVjV9-_H-4WJOtnbQi_GadXI/8748bd9bae298427/ec79ecfcb28fb10/chl_api_m
Line Number 1, Column 1: chl_api_m:1:1
Source map error: map is undefined
Resource URL: moz-extension://7392272a-fd93-4a56-acc2-c9e71fb9b7c7/model/static/DOMPurify/purify.min.js
Source Map URL: purify.min.js.map

InstallTrigger is deprecated and will be removed in the future. v1:1:92290
onmozfullscreenchange is deprecated. v1:1:92290
onmozfullscreenerror is deprecated. v1:1:92290
Request for the Private Access Token challenge. v1:1:101514
XHRGET
https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/pat/8748bd9bae298427/1713150607031/8b92a2126d59d68745a4f310477991941d95a5d38841c789d8e478a84aed4681/echyvUhlh8agPkA
[HTTP/3 401  10ms]

WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. v1:1:101514
<empty string> v1:1:101514`

![Snipaste_2024-04-15_11-11-07](https://github.com/kawa-nobu/Clean-Spam-Link-Tweet/assets/18550228/d50b8566-cc05-412c-a680-5c9137330661)

**Comment by kawa-nobu** [comment]
Thanks for the info.
CSLT does not interfere with dcard.tw at all so it does not appear that this extension is causing the Cloudflare challenge.
CSLT only works with twitter.com.

**Comment by SyaoranChang** [comment]
Maybe I misunderstood the plug-in. Sorry.

**Comment by kawa-nobu** [comment]
Don't worry about it.
I live in Japan and when I accessed dcard .tw I got a Cloudflare challenge, so I think the service itself is restricting access.
