### ISSUE TITLE
Error「報告後の動作・報告ボタンの機能割り当て」＝「ブロック」で、「ブロックできません（failed to fetch）」

### ISSUE THREAD

**Issue by nehemiaharchives** [kawa-nobu/Clean-Spam-Link-Tweet#15]
「報告後の動作・報告ボタンの機能割り当て」を「ブロック」にしている状態ですが、ここ数日「ブロックできません（failed to fetch）」というエラーが表示されるようになりました。なお、通常のブロックのUIを使った場合はブロックできました。

Verは1.9.5.1です。

ボタン押下前の状態：
![image](https://github.com/kawa-nobu/Clean-Spam-Link-Tweet/assets/40375518/a18ac150-f339-4811-85b7-559436a30767)

ボタン押下後の状態：
![image](https://github.com/kawa-nobu/Clean-Spam-Link-Tweet/assets/40375518/113af544-3594-425c-8e30-4024fd4b4cd1)

**Comment by kawa-nobu** [comment]
Issueありがとうございます。
エラーが発生したURLがtwitter .comなっていませんか?
ご確認をお願いいたします。
現状、x .comのみのサポートとしていますが、本日のアップデートでtwitter .comを非推奨でサポート予定です。

**Comment by nehemiaharchives** [comment]
確認しました。 x.com で動作確認した際は、ブロックができました。上記エラーが発生したのはURLが twitte.com となっていた場合でした。対応ありがとうございます。

**Comment by kawa-nobu** [comment]
Ver.1.9.6にてtwitter .com対応しました
