### ISSUE TITLE
FireFox版のみMV2移行

### ISSUE THREAD

**Issue by kawa-nobu** [kawa-nobu/Clean-Spam-Link-Tweet#8]
FireFoxのMV3対応化が不完全で、FireFoxをベースとしたブラウザ(Floorp)等で使えない事が判明。
早急にFireFox版としてMV2への移行を行う事。

**Comment by kawa-nobu** [comment]
FireFox用にMV2へ移行完了しました。
基本的にマニフェストを書き換えるだけで実現できた。

**Comment by Ryosuke-Asano** [comment]
こんにちは！ Floorp ブラウザーに対応していただき、ありがとうございます。

ManifestV3 なのですが、Floorp では ESR115 にアップグレード後、使用可能になります。Floorp では現在メジャーアップデートである Floorp 11 を開発中であり、Floorp 11 は ESR115 ベースになります。

Floorp 11 は来月から提供が開始されます。

３か月後にはすべての Firefox 派生で利用可能になると思います（Waterfox 等含め）なので、３か月後にアップグレードしていただけると幸いです。

**Comment by kawa-nobu** [comment]
お世話になります。
コメントありがとうございます。
本家FireFoxのMV3だと動作が怪しい部分があり、MV2へ移行して大正解でしたので
しばらくの間、FireFox版はいつでもMV3へ移行できる様に考慮しつつMV2で開発を進める予定です。
Floorpブラウザを含めて動作確認行う事を絶対条件として開発を行いますので、今後ともよろしく願い致します。
